# -*- coding: utf-8 -*-
"""Nanas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TSecEmg-tS3EEn--vXEtnb23uHr6otd
"""

import pandas as pd

df = pd.read_csv("dataset_nanas_rgb.csv")
print(df.head())

"""# Pisahkan Fitur (RGB) dan Label (Kematangan)"""

X = df[["R", "G", "B"]]  # Fitur
y = df["Label"]          # Target/kelas

"""# Bagi Data: Training dan Testing"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

"""# Latih Model Machine Learning (KNN)"""

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=6)  # Kamu bisa coba k=1, 3, 5, dst
model.fit(X_train, y_train)

"""# Evaluasi Model"""

from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("🔍 Classification Report:")
print(classification_report(y_test, y_pred))

print("🧩 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""# Percobaan Model"""

# Contoh data uji: RGB
sample = [[172, 130, 55]]
prediksi = model.predict(sample)
print(prediksi)

print(df.info())           # cek tipe data dan non-null
print(df.isnull().sum())   # pastikan tidak ada data kosong
print(df.duplicated().sum())  # pastikan tidak ada data duplikat
print(df.describe())       # cek distribusi nilai RGB

import joblib

# Simpan model
joblib.dump(model, 'model_knn.pkl')